codecov:
  token: 97781c0c-4833-4008-8a49-24fb5ec9c296
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "85...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
